### ISSUE TITLE
[BUG] Missing typescript declarations

### ISSUE THREAD

**Issue by jeswr** [rdfjs-base/data-model#38]
Thanks for the work that has gone into releasing v2 of this package. 

It appears that v2 of this package does not include the `index.d.ts` declaration that was packaged with v1.

Could this please be added back in ASAP - it took me a while to realize why this package suddenly didn't have types when using it in a new project and I imagine other devs will fall into the same trap.

**Comment by bergos** [comment]
Can't this be done with https://github.com/DefinitelyTyped/DefinitelyTyped and isn't that the native way in TypeScript? I'm not able to maintain the file, and I cannot review any related PRs. Therefore I would be happy if someone else could take care of the TypeScript language binding stuff.

**Comment by jeswr** [comment]
I've created a PR in DT that should address this. It might be worth noting somewhere in the docs the breaking API changes since v1 namely the pattern

```ts
import { quad } from '@rdfjs/data-model';
```
seems to no longer work and instead one needs to use
```ts
import factory from '@rdfjs/data-model';
const q = factory.quad(...)
```


as I noted in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57899#issuecomment-1002843264

**Comment by bergos** [comment]
Thanks for creating and pushing the DT PR.

The mentioned pattern was a side effect caused by CommonJS that somehow turned into a feature but was never part of the specification. The specification defines the [DataFactory interface](http://rdf.js.org/data-model-spec/#datafactory-interface), which this package exports. As some libraries use destructuring assignment, I added the [`bind`](https://github.com/rdfjs-base/environment/blob/master/Environment.js#L2) option to the [@rdfjs/environment package](https://github.com/rdfjs-base/environment), used by the latest version of [RDF-Ext](https://rdf-ext.org/). However, the `@rdfjs/data-model package` should be as simple as possible and according to the specification.
